---
Name: dynamicfaqsconfig
---
FAQPageController:
  managed_object: Dynamic\FAQ\Model\FAQ
  extensions:
    - Dynamic\Collection\CollectionExtension
FAQ:
  extensions:
    - Dynamic\ViewableDataObject\Extensions\ViewableDataObject
